service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10

functions:
  analyzePackage:
    handler: handler.analyzePackage
    events:
      - http:
          method: get
          path: analyzePackage
  getPackageType:
    handler: handler.getPackageType
    events:
      - http:
          method: get
          path: getPackageType

resources:  # CloudFormation template syntax
  Resources:
    packagesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: packagesTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    start:
      migrate: true